export const translations = {
    pl: {
      "Polish": "Polski",
      "English": "Angielski",
      "Login": "Zaloguj",
      "Register": "Zarejestruj",
      "Home": "Główna",
      "About us": "O nas",
      "Accomodation": "Nocleg",
      "Home visit": "Wizyta domowa",
      "Walk": "Spacer",
      "Search": "Szukaj",
      "Enter the animal": "Wpisz zwierzę",
      "Enter address": "Wpisz adres",
      "Find the best care for your pet": "Znajdź najlepszą opiekę dla swojego pupila",
      "PetCare - Your pet in good hands": "PetCare - Twój pupil w dobrych rękach",
      "Welcome to the place where you will find the best pet sitters in Poland!": "Witaj w miejscu gdzie znajdziesz najlepszych petsitterów w Polsce!",
      "PetCare was founded in 2025 as school project. We noticed from our own experience that we often lack access to a trusted pet sitter who will take care of our pet during our trips or busier days. We never wanted our dog to sit alone for long without a walk. We decided to create a place that would connect pet owners with caregivers who love animals and have free time to take care of them.": "PetCare powstało w 2025 roku jako projekt szkolny. Z własnego doświadczenia zauważyliśmy, że często brakuje nam dostępu do zaufanej opiekunki, która zaopiekuje się naszym pupilem podczas naszych podróży lub bardziej pracowitych dni. Nigdy nie chcieliśmy, aby nasz pies siedział sam przez długi czas bez spaceru. Postanowiliśmy stworzyć miejsce, które łączyłoby właścicieli zwierząt z opiekunami, którzy kochają zwierzęta i mają wolny czas, aby się nimi zająć.",
      "PetCare gives you freedom of choice!": "Petsy daje wolność wyboru!",
      "Does your pet like to run...": "Czy Twój pupil lubi biegać za piłką całe dnie...",
      "We create a community of pet parents...": "Tworzymy społeczność rodziców i opiekunów zwierząt...",
      "Warsaw": "Warszawa",
      "Dog": "Pies",
      "Cat": "Kot",
      "Read more": "Przeczytaj więcej",
      "Follow us": "Śledź nas",
      "Get in touch": "Skontakuj się",
      "Send us an email": "Wyślij nam email",
      "All right reserved": "Wszystkie prawa zastrzeżone",
      "My profile": "Mój profil",
      "My posts": "Moje ogłoszenia",
      "My pets": "Moje zwierzęta",
      "My chat": "Mój czat",
      "Save Changes": "Zapisz zmiany",
      "Logout": "Wyloguj",
      "First Name": "Imię",
      "Last Name": "Nazwisko",
      "Email": "Email",
      "Age": "Wiek",
      "Initials": "Inicjały",
      "Street": "Ulica",
      "House Number": "Numer domu",
      "City": "Miasto",
      "Region": "Województwo",
      "Postal Code": "Kod pocztowy",
      "Country": "Kraj",
      "Phone Number": "Numer telefonu",
      "Description": "Opis",
      "Stars": "Ocena",
      "Completed Orders": "Zrealizowane zlecenia",
      "No Image": "Brak zdjęcia",
      "Account Information": "Informacje o koncie",
      "Profile updated successfully!": "Profil został zaktualizowany!",
      "Loading...": "Ładowanie...",
      "Name": "Tytuł",
      "Content": "Treść",
      "Add new post": "Dodaj nowe ogłoszenie",
      "Your posts": "Twoje ogłoszenia",
      "No posts found": "Brak ogłoszeń",
      "edit": "edytuj",
      "delete": "usuń",
      "Created at": "Utworzono",
      "Updated at": "Zaktualizowano",
      "An error occurred while adding the post.": "Wystąpił błąd podczas dodawania ogłoszenia.",
      "An error occurred while deleting the post.": "Wystąpił błąd podczas usuwania ogłoszenia.",
      "Micro": "Miniaturka",
      "Small": "Mały",
      "Mediocre": "Normalny",
      "Big": "Duży",
      "Giant": "Olbrzymi",
      "Female": "Samica",
      "Male": "Samiec",
      "Add a new pet": "Dodaj nowe zwierze",
      "Your pets": "Twoje zwierzęta",
      "What drives us?": "Co nami kieruje?",
      "Filter posts": "Filtruj posty",
      "Search by name...": "Szukaj po nazwie...",
      "No results found.": "Brak wyników.",
      "All pets": "Wszystkie zwierzęta",
      "All services": "Wszystkie usługi",
      "All cities": "Wszystkie miasta",
      "Login": "Zaloguj się",
      "Register": "Zarejestruj się",
      "Login successful.": "Logowanie zakończone sukcesem.",
      "Registration successful. Now you can log in.": "Rejestracja zakończona sukcesem. Teraz możesz się zalogować.",
      "Registration failed": "Rejestracja nie powiodła się",
      "failed. Please try again.": "nie powiodło się. Spróbuj ponownie.",
      "Don't have an account yet?": "Nie masz jeszcze konta?",
      "Already have an account?": "Masz już konto?",
      "Register now": "Zarejestruj się teraz",
      "Login now": "Zaloguj się teraz",
      "Email": "Email",
      "Password": "Hasło",
      "Chat": "Czat",
      "Enter title...": "Wpisz tytuł...",
      "Enter message...": "Wpisz wiadomość...",
      "Recipient": "Odbiorca",
      "Send": "Wyślij",
      "Live messages": "Wiadomości na żywo",
      "Your messages": "Twoje wiadomości",
      "From": "Od",
      "Pet added successfully!": "Pomyślnie dodano nowego zwierzaka!",
      "An error occurred while adding the pet.": "Błąd podczas dodawania nowego zwierzaka",
      "Pet deleted successfully!": "Pomyślnie usunięto zwierzaka!",
      "An error occurred while deleting the pet.": "Błąd podczas usuwania zwierzaka",
      "Post added successfully!": "Pomyślnie dodano nowy post!",
      "An error occurred while adding the post.": "Błąd podczas dodawania nowego posta",
      "Post deleted successfully!": "Pomyślnie usunięto post!",
      "An error occurred while deleting the post.": "Błąd podczas usuwania posta",
      "Login successful.": "Zalogowano pomyślnie",
      "Registration successful. Now you can log in.": "Zarejestrowano pomyślnie. Teraz możesz się zalogować",
      "Our goal is to combine love for animals with the need for safe care. We want to create a space where pet owners can confidently entrust their dog, cat, or other animal to trusted caregivers. Our mission is not only to provide safety and comfort to animals, but also joy to both them and their caregivers.":"Naszym celem jest połączenie miłości do zwierząt z potrzebą bezpiecznej opieki. Chcemy stworzyć przestrzeń, w której właściciele zwierząt domowych mogą z przekonaniem powierzyć swojego psa, kota lub inne zwierzę zaufanym opiekunom. Naszą misją jest nie tylko zapewnienie bezpieczeństwa i komfortu zwierzętom, ale także radości zarówno im, jak i ich opiekunom.",
      "We believe every animal deserves care, attention, and love at the highest level, and every caregiver deserves trust and the opportunity to share their passion for animals. Thanks to our platform, caregivers and pet owners find themselves in one place, making it easier to build a relationship based on trust, understanding, and love for animals.": "Wierzymy, że każde zwierzę zasługuje na opiekę, uwagę i miłość na najwyższym poziomie, a każdy opiekun zasługuje na zaufanie i możliwość dzielenia się swoją pasją do zwierząt. Dzięki naszej platformie opiekunowie i właściciele zwierząt domowych znajdują się w jednym miejscu, co ułatwia budowanie relacji opartej na zaufaniu, zrozumieniu i miłości do zwierząt.",
      "We want each interaction to be a step towards greater comfort and happiness — for animals and their owners. Our goal is not only to offer services, but also to build a community where everyone feels safe and happy.": "Chcemy, aby każda interakcja była krokiem w stronę większego komfortu i szczęścia — dla zwierząt i ich właścicieli. Naszym celem jest nie tylko oferowanie usług, ale także budowanie społeczności, w której każdy czuje się bezpiecznie i szczęśliwie.",
      "Conditions": "Warunki",
      "Add order": "Dodaj zlecenie",
      "Confirm": "Potwierdź",
      "Close": "Zamknij",
      "Your orders": "Twoje zlecenia",
      "My account": "Moje konto",
      "My orders": "Moje zlecenia",
      "Image": "Zdjęcie",
      "Edit post": "Edytuj post",
      "Are you sure you want to delete this post": "Czy jesteś pewnie że chcesz usunąć ten post",
      "Add new pet": "Dodaj nowe zwierzę",
    },
    en: {
      "Polish": "Polish",
      "English": "English",
      "Login": "Login",
      "Register": "Register",
      "Home": "Home",
      "About us": "About us",
      "Accomodation": "Accomodation",
      "Home visit": "Home visit",
      "Walk": "Walk",
      "Search": "Search",
      "Enter the animal": "Enter the animal",
      "Enter address": "Enter address",
      "Find the best care for your pet": "Find the best care for your pet",
      "PetCare - Your pet in good hands": "PetCare - Your pet in good hands",
      "Welcome to the place where you will find the best pet sitters in Poland!": "Welcome to the place where you will find the best pet sitters in Poland!",
      "PetCare was founded in 2025 as school project. We noticed...": "PetCare was founded in 2025 as school project...",
      "PetCare gives you freedom of choice!": "PetCare gives you freedom of choice!",
      "Does your pet like to run...": "Does your pet like to run after a ball all day...",
      "We create a community of pet parents...": "We create a community of pet parents and caregivers...",
      "Warsaw": "Warsaw",
      "Dog": "Dog",
      "Cat": "Cat",
      "Read more": "Read more",
      "Follow us": "Follow us",
      "Get in touch": "Get in touch",
      "Send us an email": "Send us an email",
      "All right reserved": "All right reserved",
      "My profile": "My profile",
      "My posts": "My posts",
      "My pets": "My pets",
      "My chat": "My chat",
      "Save Changes": "Save Changes",
      "Logout": "Logout",
      "First Name": "First Name",
      "Last Name": "Last Name",
      "Email": "Email",
      "Age": "Age",
      "Initials": "Initials",
      "Street": "Street",
      "House Number": "House Number",
      "City": "City",
      "Region": "Region",
      "Postal Code": "Postal Code",
      "Country": "Country",
      "Phone Number": "Phone Number",
      "Description": "Description",
      "Stars": "Stars",
      "Completed Orders": "Completed Orders",
      "No Image": "No Image",
      "Account Information": "Account Information",
      "Profile updated successfully!": "Profile updated successfully!",
      "Loading...": "Loading...",
      "Name": "Name",
      "Content": "Content",
      "Add new post": "Add new post",
      "Your posts": "Your posts",
      "No posts found": "No posts found",
      "edit": "edit",
      "delete": "delete",
      "Created at": "Created at",
      "Updated at": "Updated at",
      "An error occurred while adding the post.": "An error occurred while adding the post.",
      "An error occurred while deleting the post.": "An error occurred while deleting the post.",
      "Micro": "Micro",
      "Small": "Small",
      "Mediocre": "Mediocre",
      "Big": "Big",
      "Giant": "Giant",
      "Female": "Female",
      "Male": "Male",
      "Add a new pet": "Add a new pet",
      "Your pets:": "Your pets:",
      "Conditions": "Conditions",
      "Add order": "Add order",
      "Confirm": "Confirm",
      "Close": "Close",
      "Your orders": "Your orders",
      "My account": "My account",
      "My orders": "My orders",
      "Image": "Image",
      "Edit post": "Edit post",
      "Are you sure you want to delete this post": "Are you sure you want to delete this post",
      "Add new pet": "Add new pet",
    }
  };
  